# Generated by Django 5.1.6 on 2025-02-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('FIC', 'Fiction'), ('NON', 'Non-Fiction'), ('SCI', 'Science'), ('HIS', 'History'), ('BIO', 'Biography'), ('FAN', 'Fantasy'), ('THR', 'Thriller'), ('ROM', 'Romance'), ('HOR', 'Horror'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('rating', models.PositiveSmallIntegerField()),
                ('language', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='')),
                ('started_reading', models.DateTimeField(auto_now_add=True)),
                ('finished_reading', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
