# Generated by Django 5.1.6 on 2025-02-15 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookry', '0002_author_genre_remove_book_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_Author',
            new_name='BookAuthor',
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookry.book')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookry.genre')),
            ],
        ),
        migrations.DeleteModel(
            name='Book_Genre',
        ),
    ]
