# Generated by Django 5.1.6 on 2025-02-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookry', '0004_remove_bookauthor_author_remove_bookauthor_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
        migrations.AddField(
            model_name='book',
            name='finished_reading',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FIC', 'Fiction'), ('NON', 'Non-Fiction'), ('SCI', 'Science'), ('HIS', 'History'), ('BIO', 'Biography'), ('FAN', 'Fantasy'), ('THR', 'Thriller'), ('ROM', 'Romance'), ('HOR', 'Horror'), ('OTH', 'Other')], default='OTH', max_length=3),
        ),
        migrations.AddField(
            model_name='book',
            name='started_reading',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
