# Generated by Django 5.1.6 on 2025-02-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookry', '0005_remove_book_isbn_remove_book_pages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FIC', 'Fiction'), ('NON', 'Non-Fiction'), ('SCI', 'Science'), ('HIS', 'History'), ('BIO', 'Biography'), ('FAN', 'Fantasy'), ('THR', 'Thriller'), ('ROM', 'Romance'), ('HOR', 'Horror'), ('OTH', 'Other')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='bookry.genre'),
        ),
    ]
