# Generated by Django 5.1.6 on 2025-02-16 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookry', '0007_remove_book_genre_book_genres_alter_genre_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='name',
        ),
        migrations.AddField(
            model_name='genre',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookry.book'),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
