# Generated by Django 5.1.6 on 2025-02-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookry', '0008_remove_book_genres_remove_genre_name_genre_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='books', to='bookry.genre'),
        ),
    ]
