# Generated by Django 5.1.6 on 2025-02-17 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookry', '0009_remove_genre_book_book_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genres',
        ),
    ]
