# Generated by Django 5.1.6 on 2025-02-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookry', '0010_rename_genre_book_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
